version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      applies-to: version-updates
      update-types:
        - "minor"
        - "patch"
    assignees:
      - "johnnyfleet"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      applies-to: version-updates
      update-types:
        - "minor"
        - "patch"
    assignees:
      - "johnnyfleet"