language: bash
sudo: required

services:
  - docker

before_script:
  - docker pull johnnyfleet/bliss || true
  
script:
  - VERSION=$(curl -s http://www.blisshq.com/app/latest-linux-version | awk -F'[-.]' '{print $5}')
  - docker build --pull -t johnnyfleet/bliss:latest -t johnnyfleet/bliss:$VERSION .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
