language: bash
sudo: required

services:
  - docker

before_install:
  - docker build -t johnnyfleet/bliss:latest -t johnnyfleet/bliss:20180529 .
  
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
