on:
  push:
    branches:    
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'   # excludes master

jobs:
  build-secure:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - run: docker build . -t johnnyfleet/bliss:${{ github.sha }}

    - name: Scan image
      id: scan
      uses: anchore/scan-action@v3
      with:
        image: johnnyfleet/bliss:${{ github.sha }}
        fail-build: false
        acs-report-enable: true

    - name: Inspect action SARIF report
      run: cat ${{ steps.scan.outputs.sarif }}
    
    - name: upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}

      
      
    - uses: Azure/container-scan@v0
      with:
        image-name: johnnyfleet/bliss:${{ github.sha }}