---
name: Parallel Test

on: push

jobs:
  Build-Docker:
    strategy:
      fail-fast: false
      matrix:
        bliss_version: [latest,20220531,20220513,20220503,20220419,20220329]
        platforms: [linux/amd64,linux/arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: ${{ matrix.platforms }}
          tags: johnnyfleet/bliss-test:${{ matrix.bliss_version }}