---
name: Test Python Echo

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - run: |
          output=$(test-echo.py)
          echo "::set-output name=changelog::$output"
        id: step1
      - name: Print changelog
        run: echo "${{ steps.step1.outputs.changelog }}